TRUNCATE WAKA.sop_document RESTART IDENTITY;
TRUNCATE WAKA.documents RESTART IDENTITY CASCADE;
INSERT INTO waka.documents (grp, grp_seq, html_template, sub_grp, sub_grp_seq, doc_name, control_name, doc_seq, ui_img_file_name, has_child, view_text, fields, is_completed, is_alert, is_selected, created_by) VALUES
('Government',1,'template2','Issuance of General Documents',1,'Issuance of General Documents','IssGenDocs',1,null, true,null,'[{"group":"Issuance of General Documents","fields":["field0"], "field0":{"type":"chipset-mandatory", "field":[{"fieldname":"","selLabel":"Selected general documents will be issued", "value":["Certificate of Origin"], "options":[],"unselLabel":"", "controlname": "IssGenDocsName", "child":[]}]}}]',false,false,null,1),
('Government',1,'template2','Issuance of Commodity Specific Documents',2,'Issuance of Commodity Specific Documents','IssCommSpecDocs',2,null, true,null,'[{"group":"Issuance of Commodity Specific Documents","fields":["field0"], "field0":{"type":"chipset", "field":[{"fieldname":"","selLabel":"Selected commodity specific documents will be issued", "value":["Electrical License"], "options":["Electrical License","Food Product Certificate"],"unselLabel":"Add more documents", "controlname": "IssCommSpecDocsName", "child":[]}]}}]',false,false,null,1),
('Commercial',2,'template2','Issuance of Commercial Invoice',1,'Issuance of Commercial Invoice','IssCommInv',1,null, true,null,'[{"group":"Issuance of Commercial Invoice","label":"Selected commercial invoice format will be available on the platform", "fields":["field0"], "field0":{"type":"select", "field":[{"fieldname":"Select Format", "placeholder":"Select Format", "options":["Use my format","Use WAKA standard format"], "methodName":"getIssCommInvtFormat", "value":null, "controlname":"IssCommDocsSelect", "child":[{"type":"chipset-file", "field":[{"fieldname":"","selLabel":"","uploadedFileName":[], "value":[], "options":[],"unselLabel":"", "controlname": "IssCommDocsFile", "child":[]}]}]}]}},{"group":"Define the number of documents required","fields":["field0"], "field0":{"type":"inlineedit", "field":[{"pretext":"Number of originals", "value":7, "posttext":"", "range":[0,50],"controlname":"IssCommInvNoOfDocs", "child":[]},{"pretext":"and number of copies", "value":10, "posttext":"", "range":[0,50],"controlname":"IssCommInvNoofCopies", "child":[]}]}}]',false,false,true,1),
('Commercial',2,'template2','Issuance of Packing List',2,'Issuance of Packing List','IssPackList',2,null, true,null,'[{"group":"Issuance of Packing List","label":"Selected packing list format will be available on the platform", "fields":["field0"], "field0":{"type":"select", "field":[{"fieldname":"Select Format", "placeholder":"Select Format", "options":["Use my format","Use WAKA standard format"], "methodName":"getIssPackListFormat", "value":[], "controlname":"IssPackListSelect", "child":[{"type":"chipset-file", "field":[{"fieldname":"","selLabel":"","uploadedFileName":[], "value":[], "options":[],"unselLabel":"", "controlname": "IssPackListFile", "child":[]}]}]}]}},{"group":"Define the number of documents required","fields":["field0"], "field0":{"type":"inlineedit", "field":[{"pretext":"Number of originals", "value":7, "posttext":"", "range":[0,30],"controlname":"IssPackListNoOfDocs", "child":[]},{"pretext":"and number of copies", "value":98, "posttext":"", "range":[0,100],"controlname":"IssPackListNoofCopies", "child":[]}]}}]',false,false,true,1),
('Commercial',2,'template2','Issuance of MSDS (Material Safety Data Sheet)',3,'Issuance of MSDS (Material Safety Data Sheet)','IssMsds',3,null, true,null,'[{"group":"Issuance of MSDS (Material Safety Data Sheet)","label":"MSDS document will be managed by Freight Forwarder", "fields":["field0"], "field0":[{"controlname":"IssMsdsName"}]}]',false,false,true,1),
('Shipping',3,'template2','Issuance of Forwarders Cargo Receipt/ House Bill of Lading/ House Sea Waybill',1,'Issuance of Forwarders Cargo Receipt/ House Bill of Lading/ House Sea Waybill','IssForCargoBills',1,null, true,null,'[{"group":"Selected document type that needs to be issued", "fields":["field0"], "field0":{"type":"chipset", "field":[{"fieldname":"",  "selLabel":"Selected parties","options":["Forwarders Cargo Receipt","House Bill of Lading/ House Sea Waybill"], "value":["Forwarders Cargo Receipt","House Bill of Lading/ House Sea Waybill"], "controlname":"IssForCargoBillsDocType","unselLabel":"Unselected parties", "child":[]}]}},{"group":"Define the number of documents required","fields":["field0"], "field0":{"type":"inlineedit", "field":[{"pretext":"Number of originals", "value":7, "posttext":"and number of copies", "range":[0,30],"controlname":"IssForCargoRemainderToGenerate", "child":[]},{"pretext":"", "value":98, "posttext":"", "range":[0,100],"controlname":"IssForCargoNoofCopies", "child":[]}]}},{"group":"Reminder for issuance of documents","is_alert":true ,"fields":["field0"], "field0":{"type":"inlineedit", "field":[{"pretext":"FCR/HBL to be issued", "value":7, "posttext":"days after", "range":[0,30],"controlname":"FCRRemainderToGenerate", "child":[{"type":"select", "field":[{"fieldname":"Select Data Type", "options":["Cargo Receiving Date","CFS Cutoff Date"], "value":null, "controlname":"FCRSelectDataType", "child":[]}]}]}]}},{"group":"","fields":["field0"], "field0":{"type":"multi", "field":[{"fieldname":"House Bill of Lading or House Sea WayBill must be dated and issued on the day the cargoes are shipped on board", "value":true, "controlname":"HouseBillIssued", "child": []},{"fieldname":"Remarks on the conditions of the cargoes as stipulated on the Dock Receipts are to be stated on the FCR or House Bill of Lading or House Sea Waybill or House Sea Waybill", "value":true, "controlname":"RemarkCargoDock", "child": []},{"fieldname":"Issue Received of Shipment FCR for overflow of cargoes", "value":true, "controlname":"IssueReceiveShip", "child": []},{"fieldname":"Allow issue one set of FCR or House Bill of Lading or House Sea Waybill per split shipment", "value":true, "controlname":"AllowIssueFCR", "child": []}]}},{"group":"Selected party types and the respective details will be mentioned in the issued documents", "fields":["field0"], "field0":{"type":"chipset", "field":[{"fieldname":"",  "selLabel":"Selected parties","options":["Notify Party","Supplier","Principal"], "value":["Supplier","Principal"], "controlname":"IssForCargoBillsSelectedParty","unselLabel":"Unselected parties", "child":[]}]}}]',false,true,true,1),
('Shipping',3,'template2','Issuance of Master Bill of Lading/Sea Waybill',2,'Issuance of Master Bill of Lading/Sea Waybill','IssMasterBills',2,null, true,null,'[{"group":"Select the type of documents that needs to be issued ","label":"", "fields":["field0"], "field0":{"type":"select", "field":[{"fieldname":"Select type", "placeholder":"Select type", "options":["Master Bill of Lading","Master Sea Waybill"], "methodName":"SelectBills", "value":[], "controlname":"LadingSeaWayBills", "child":[]}]}},{"group":"Define the number of documents required","fields":["field0"], "field0":{"type":"inlineedit", "field":[{"pretext":"Number of originals", "value":7, "posttext":"", "range":[0,30],"controlname":"IssMasterBillsRemainderToGenerate", "child":[]},{"pretext":"and number of copies", "value":98, "posttext":"", "range":[0,100],"controlname":"IssMasterBillsNoofCopies", "child":[]}]}},{"group":"Reminder for issuance of documents","label":"", "fields":["field0"], "field0":{"type":"inlineedit", "field":[{"pretext":"Master Bill of Lading/Sea WayBill to be issued", "is_alert":true, "value":7, "posttext":"days after Vessel Departure Date", "range":[0,30],"controlname":"IssMasterBillsRemGenDocsName", "child":[]}]}},{"group":"","fields":["field0"], "field0":{"type":"multi", "field":[{"fieldname":"Issue One Single Master Bill of Lading/Sea Waybill if Containers with same Ship Mode, From same Loading Port, To same Discharging Port, on the same Vessel Voyage and Carrier", "value":true, "controlname":"IssOneSingleMaster", "child": []}]}},{"group":"Selected party types and the respective details will be mentioned in the issued documents", "fields":["field0"], "field0":{"type":"chipset", "field":[{"fieldname":"",  "selLabel":"Selected parties","options":["Notify Party","Supplier","Principal"], "value":["Supplier","Principal"], "controlname":"IssMasterBillsSelectedParty","unselLabel":"Unselected parties", "child":[]}]}}]',false,true,true,1),
('Shipping',3,'template2','Issuance of Bill of Lading/Sea Waybill from Coloader',3,'Issuance of Bill of Lading/Sea Waybill from Coloader','IssColoaderBills',2,null, true,null,'[{"group":"Define the number of documents required","fields":["field0"], "field0":{"type":"inlineedit", "field":[{"pretext":"Number of originals", "value":7, "posttext":"and number of copies", "range":[0,30],"controlname":"IssColoaderBillsNoofCopies", "child":[]},{"pretext":"", "value":98, "posttext":"", "range":[0,100],"controlname":"IssColoaderBillsNoofCopiesName", "child":[]}]}},{"group":"Reminder for issuance of documents","label":"", "is_alert":true ,"fields":["field0"], "field0":{"type":"inlineedit", "field":[{"pretext":"FCR/HBL to be issued", "value":7, "posttext":"days after Vessel Departure", "range":[0,30],"controlname":"RemIssDoc", "child":[]}]}},{"group":"","fields":["field0"], "field0":{"type":"multi", "field":[{"fieldname":"Issue One Single House Bill of Lading/Sea Waybill if Containers with same Ship Mode, From same Loading Port, To same Discharging Port, on the same Vessel Voyage and Carrier", "value":true, "controlname":"IssShipMode", "child": []}]}},{"group":"Selected party types and the respective details will be mentioned in the issued documents", "fields":["field0"], "field0":{"type":"chipset", "field":[{"fieldname":"",  "selLabel":"Selected parties","options":["Notify Party","Supplier","Principal"], "value":["Supplier","Principal"], "controlname":"IssShipModeSelectedParty","unselLabel":"Unselected parties", "child":[]}]}}]',false,true,true,1),
('Shipping',3,'template2','Issuance of Master Air Waybill and House Air Waybill',4,'Issuance of Master Air Waybill and House Air Waybill','IssMasterAirBills',2,null, true,null,'[{"group":"Define the number of documents required","fields":["field0"], "field0":{"type":"inlineedit", "field":[{"pretext":"Number of originals", "value":7, "posttext":"and number of copies", "range":[0,30],"controlname":"IssMasterAirBillsNoOfCopies", "child":[]},{"pretext":"", "value":98, "posttext":"", "range":[0,100],"controlname":"IssMasterAirBillsNoOfCopiesName", "child":[]}]}},{"group":"Selected party types and the respective details will be mentioned in the issued documents", "fields":["field0"], "field0":{"type":"chipset", "field":[{"fieldname":"",  "selLabel":"Selected parties","options":["Notify Party","Supplier","Principal"], "value":["Supplier","Principal"], "controlname":"IssMasterAirBillsSelectedParty","unselLabel":"Unselected parties", "child":[]}]}}]',false,false,true,1),
('Shipping',3,'template2','Issuance of Container Manifest',5,'Issuance of Container Manifest','IssContManifest',2,null, true,null,'[{"group":"Issuance of Container Manifest","label":"Required to attach the consolidated information pertaining to the contents in the container", "fields":["field0"], "field0":[{"controlname":"IssContManifestName"}]}]',false,false,null,1),
('Documents Despatch',4,'template2','Reminder to Generate Documents Despatch',1,'Reminder to Generate Documents Despatch','RemGenDocsDis',1,null, true,null,'[{"group":"Reminder to Generate Documents Despatch","label":"", "is_alert":true ,"fields":["field0"], "field0":{"type":"inlineedit", "field":[{"pretext":"Documents will be despatched", "value":7, "posttext":"days after Vessel Departure", "range":[0,30],"controlname":"RemGenDocsDisName", "child":[]}]}}]',false,true,null,1),
('Documents Despatch',4,'template2','Document Despatch to Parties',2,'Document Despatch to Parties','DocDispToParty',2,null, true,null,'[{"group":"Document Despatch to Parties","label":"Selected parties will receive despatched documents", "fields":["field0"], "field0":{"type":"select-users", "field":[{"fieldname":"Principal Details", "placeholder":"Select Principal Users", "options":[], "methodName":"getConsigneeContacts", "value":[], "controlname":"DocDispToPartyPrincipal", "child":[{"type":"chipset", "field":[{"fieldname":"","selLabel":"", "value":[], "options":[],"unselLabel":"", "controlname": "DocDispToPartyPrincipalUsers", "child":[]}]}]},{"fieldname":"Freight Forwarder Details", "placeholder":"Select Forwarder Users", "options":[], "methodName":"getFFContacts", "value":[], "controlname":"DocDispToPartyForwarder", "child":[{"type":"chipset", "field":[{"fieldname":"","selLabel":"", "value":[], "options":[],"unselLabel":"", "controlname": "DocDispToPartyForwarderUsers", "child":[]}]}]}]}}]',false,false,null,1);

----UPDATE QUERY

UPDATE waka.sop_pob SET fields = '[{"group":"Purchase Order Posting","fields":["field0"], "field0":{"type":"inlineedit", "field":[{"pretext":"PO must be posted to waka platform", "value":7, "posttext":"Days prior to", "range":[0,30],"controlname":"DatePriorCRD", "child":[{"type":"select", "field":[{"fieldname":"Select Data Type", "options":["Cargo Ready Date","Contract Shipment Date","Into DC Date"], "value":null, "controlname":"POPSelectDataType", "child":[]}]}]}]}},{"group":"Exception Alert for Purchase Order Uploaded","label":"The selected parties must be notified incase of an exception alert", "fields":["field0"], "field0":{"type":"select-users", "field":[{"fieldname":"Principal Details", "placeholder":"Select Principal Users", "options":[], "methodName":"getConsigneeContacts", "value":[], "controlname":"POPPUEPrincipal", "child":[{"type":"chipset", "field":[{"fieldname":"","selLabel":"", "value":[], "options":[],"unselLabel":"", "controlname": "POPPUEPrincipalUsers", "child":[]}]}]},{"fieldname":"Freight Forwarder", "placeholder":"Select Frieght Forwarder Users", "options":[], "methodName":"getFFContacts", "value":[], "controlname":"POPPUEForwarder", "child":[{"type":"chipset", "field":[{"fieldname":"","selLabel":"", "value":[], "options":[],"unselLabel":"", "controlname": "POPPUEForwarderUsers", "child":[]}]}]}]}}]' WHERE pob_id = 1;

UPDATE waka.po_booking SET fields = '[{"group":"Purchase Order Posting","fields":["field0"], "field0":{"type":"inlineedit", "field":[{"pretext":"PO must be posted to waka platform", "value":7, "posttext":"Days prior to", "range":[0,30],"controlname":"DatePriorCRD", "child":[{"type":"select", "field":[{"fieldname":"Select Data Type", "options":["Cargo Ready Date","Contract Shipment Date","Into DC Date"], "value":null, "controlname":"POPSelectDataType", "child":[]}]}]}]}},{"group":"Exception Alert for Purchase Order Uploaded","label":"The selected parties must be notified incase of an exception alert", "fields":["field0"], "field0":{"type":"select-users", "field":[{"fieldname":"Principal Details", "placeholder":"Select Principal Users", "options":[], "methodName":"getConsigneeContacts", "value":[], "controlname":"POPPUEPrincipal", "child":[{"type":"chipset", "field":[{"fieldname":"","selLabel":"", "value":[], "options":[],"unselLabel":"", "controlname": "POPPUEPrincipalUsers", "child":[]}]}]},{"fieldname":"Freight Forwarder", "placeholder":"Select Frieght Forwarder Users", "options":[], "methodName":"getFFContacts", "value":[], "controlname":"POPPUEForwarder", "child":[{"type":"chipset", "field":[{"fieldname":"","selLabel":"", "value":[], "options":[],"unselLabel":"", "controlname": "POPPUEForwarderUsers", "child":[]}]}]}]}}]' WHERE pob_id = 1;

----- SOP Cargo Handling 29112021

UPDATE waka.cargo_handling SET fields = '[{"group":"Free Storage Details for LCL", "fields":["field0","field1"], "field0":{"type":"inlineedit","subgroup":"This information is given by the service providers for the selected origin ports."}, "field1":{"type":"table", "field":[{"source":"portStorageColl", "child":[]}]}}]' WHERE ch_id = 1;

UPDATE waka.cargo_handling SET fields = '[{"group":"Action required early delivery request for LCL", "fields":["field0"], "field0":{"type":"select", "field":[{"fieldname":"Select action", "options":["Always reject","Upon principal’s approval"], "value":"Always reject", "controlname":"CRAEDLCLOptions", "child":[]}]}}]' WHERE ch_id = 4;

UPDATE waka.cargo_handling SET fields = '[{"group":"Fumigation", "fields":["field0"], "field0":{"type":"inlineedit","subgroup":"Select the service to receive a certificate for fumigated cargo."}}]' WHERE ch_id = 6;

UPDATE waka.cargo_handling SET fields = '[{"group":"Split PO into Multiple Container", "fields":["field0"], "field0":{"type":"inlineedit","subgroup":"Allow freight forwarder to split your POs into multiple containers."}}]' WHERE ch_id = 15;

UPDATE waka.cargo_handling SET fields = '[{"group":"Allow Loading with Mix-Packaging", "fields":["field0"], "field0":{"type":"inlineedit","subgroup":"Allow carrier to load with mix-packaging ."}}]' WHERE ch_id = 18;

----SOP Carrier 30112021

DROP TABLE IF EXISTS waka.carrier CASCADE;
CREATE TABLE waka.carrier(
	carrier_id SERIAL PRIMARY KEY,
	html_template VARCHAR DEFAULT 'template2',
	grp VARCHAR NOT NULL,
	grp_seq INT,
	sub_grp VARCHAR,
	sub_grp_seq INT,
	carrier_name VARCHAR NOT NULL,
	control_name VARCHAR NOT NULL UNIQUE,
	carrier_seq INT,
	ui_img_file_name varchar,
	has_child BOOLEAN NOT NULL default false,
	fields JSON,
	view_text VARCHAR,
	is_alert BOOLEAN DEFAULT false,
	is_deleted BOOLEAN DEFAULT false,
	is_selected BOOLEAN DEFAULT false,
	created_by INT NOT NULL REFERENCES waka.login_user(user_id) ON DELETE CASCADE,
	created_on TIMESTAMPTZ NOT NULL DEFAULT now(),
	modified_by INT REFERENCES waka.login_user(user_id) ON DELETE CASCADE,
	modified_on TIMESTAMPTZ
);

DROP TABLE IF EXISTS waka.sop_carrier;
CREATE TABLE waka.sop_carrier(
	sop_carrier_id SERIAL PRIMARY KEY,
	sop_id INT NOT NULL REFERENCES waka.sop(sop_id) ON DELETE CASCADE,
    carrier_id INT NOT NULL REFERENCES waka.carrier(carrier_id) ON DELETE CASCADE,
	sop_port_id INT REFERENCES waka.sop_port(sop_port_id) ON DELETE CASCADE,
	fields JSON NULL,
	is_selected BOOLEAN DEFAULT false,
	created_by INT NOT NULL REFERENCES waka.login_user(user_id) ON DELETE CASCADE,
	created_on TIMESTAMPTZ NOT NULL DEFAULT now(),
	modified_by INT REFERENCES waka.login_user(user_id) ON DELETE CASCADE,
	modified_on TIMESTAMPTZ,
	UNIQUE (sop_id, carrier_id)
);

INSERT INTO waka.carrier (grp, grp_seq, html_template, sub_grp, sub_grp_seq, carrier_name, control_name, carrier_seq, ui_img_file_name, has_child, view_text, fields, is_alert, is_selected , created_by) VALUES
('Carrier Requirements',1,'template2','Carrier Forecast',1,'Carrier Forecast','CarrierForcast',1,null, true,null,'[{"group":"Frequency of Forecast to Carrier","fields":["field0"], "field0":{"type":"inlineedit", "is_alert": true, "field":[{"pretext":"Reminder for carrier to generate periodic forecast for every", "value":2, "posttext":"weeks", "range":[1,4],"controlname":"FFCForcast", "child":[]}]}},{"group":"Data to be used in Forecast", "fields":["field0"], "field0":{"type":"chipset", "field":[{"fieldname":"",  "selLabel":"Select the type of data that should be used in carrier forecast","options":["PO Data","Historical Shipment Data"], "value":["PO Data","Historical Shipment Data"], "controlname":"DUForcast","unselLabel":"Add more details", "child":[]}]}},{"group":"Start day of the week for the Forecast", "fields":["field0"], "field0":{"type":"inlineedit", "field":[{"pretext":"Carrier forecast should commence on","value":7,"posttext":"","range":[0,30],"controlname":"ForSelNoShow", "child":[{"type":"select", "field":[{"fieldname":"Select Day", "placeholder":"Select Type", "posttext":"of every week", "options":["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"], "methodName":"getDay", "value":[], "controlname":"CFDay", "child":[]}]}]}]}}]',true,true,1),
('Carrier Requirements',1,'template2','Sailing Schedule Maintenance',2,'Sailing Schedule Maintenance','SSMaintain',2,null, true,null,'[{"group":"Arrange periodic update of Sailing Schedule","fields":["field0"], "field0":{"type":"inlineedit", "field":[{"pretext":"Receive updated sailing schedule every", "value":2, "posttext":"weeks", "range":[1,4],"controlname":"PUSSMaintain", "child":[]}]}},{"group":"Sailing Schedule Details", "fields":["field0"], "field0":{"type":"chipset", "field":[{"fieldname":"",  "selLabel":"Selected details must be mentioned in the sailing schedule","options":["VGM Cutoff","SI Cutoff","CFS Opening","CFS Closing","CY Opening","CY Closing","Carrier Name","Service Routes","Vessel Name","Voyage","Loading Port","Discharging Port","ETD","ETA"], "value":["Carrier Name","Service Routes","Vessel Name","Voyage","Loading Port","Discharging Port","ETD","ETA"], "controlname":"DUForcast","unselLabel":"Add more details", "child":[]}]}},{"group":"Email sailing schedule to the selected parties","label":"Selected parties must be notified on sailing schedule via email", "fields":["field0"], "field0":{"type":"select-users", "field":[{"fieldname":"Principal Details", "placeholder":"Select Principal Users", "options":[], "methodName":"getConsigneeContacts", "value":[], "controlname":"EmailSailPrincipal", "child":[{"type":"chipset", "field":[{"fieldname":"","selLabel":"", "value":[], "options":[],"unselLabel":"", "controlname": "DocDispToPartyPrincipalUsers", "child":[]}]}]},{"fieldname":"Freight Forwarder Details", "placeholder":"Select Forwarder Users", "options":[], "methodName":"getFFContacts", "value":[], "controlname":"EmailSailForwarder", "child":[{"type":"chipset", "field":[{"fieldname":"","selLabel":"", "value":[], "options":[],"unselLabel":"", "controlname": "DocDispToPartyForwarderUsers", "child":[]}]}]}]}},{"group":"Sailing schedule reminder via email", "fields":["field0"], "field0":{"type":"inlineedit", "is_alert": true, "field":[{"pretext":"Selected parties must receive sailing schedule email every","value":7,"posttext":"","range":[0,30],"controlname":"ForSelNoShow", "child":[{"type":"select", "field":[{"fieldname":"Select Day", "placeholder":"Select Type", "posttext":"of the week", "options":["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"], "methodName":"getDay", "value":[], "controlname":"CFDay", "child":[]}]}]}]}}]',true,true,1),
('Carrier Requirements',1,'template2','Booking Shortfall/Rollover Exception',3,'Booking Shortfall/Rollover Exception','BSorRExp',3,null, true,null,'[{"group":"Select the details for booking shortfall/rollover exception report","fields":["field0"], "field0":{"type":"chipset-mandatory", "field":[{"fieldname":"","selLabel":"", "value":["Status of Booking/Container","Landing Port","Discharging Port","Vessel Name","Voyage","Number of Confirmed Containers","Containers Type","Containers Size","Number of Rollover Containers","PO Details"], "options":[],"unselLabel":"", "controlname": "BSorRExpName", "child":[]}]}}]',false,true,1);

----SOP Carrier Allocation and Preference 10122021

DROP TABLE IF EXISTS waka.carrier_allocation_interval;
CREATE TABLE waka.carrier_allocation_interval(
	carrier_interval_id SERIAL PRIMARY KEY,
	carrier_interval_name VARCHAR NOT NULL,
	created_by INT NOT NULL REFERENCES waka.login_user(user_id) ON DELETE CASCADE,
	created_on TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO waka.carrier_allocation_interval (carrier_interval_name, created_by, created_on) VALUES 
('Weekly',1,NOW()),
('Monthly',1,NOW()),
('Quarterly',1,NOW()),
('Yearly',1,NOW());

DROP TABLE IF EXISTS waka.sop_carrier_allocations CASCADE;
DROP TABLE IF EXISTS waka.sop_carrier_allocation;
CREATE TABLE waka.sop_carrier_allocation(
	sop_ca_id SERIAL PRIMARY KEY,
	sop_id INT NOT NULL REFERENCES waka.sop(sop_id) ON DELETE CASCADE,
	sop_port_id INT REFERENCES waka.sop_port(sop_port_id) ON DELETE CASCADE,
	effective_start_date TIMESTAMPTZ NOT NULL,
	effective_end_date TIMESTAMPTZ NOT NULL,
	allocated_by VARCHAR NOT NULL,
	carrier INT[],
	carrier_preference INT[],
	allocation_type VARCHAR NOT NULL,
	allocation_interval INT REFERENCES waka.carrier_allocation_interval(carrier_interval_id) ON DELETE CASCADE,
	unit_of_allocation VARCHAR NOT NULL,
	service_type VARCHAR,
	allocation_value JSON,
	created_by INT NOT NULL REFERENCES waka.login_user(user_id) ON DELETE CASCADE,
	created_on TIMESTAMPTZ NOT NULL DEFAULT now(),
	modified_by INT REFERENCES waka.login_user(user_id) ON DELETE CASCADE,
	modified_on TIMESTAMPTZ,
	UNIQUE (sop_id, sop_port_id, effective_start_date, effective_end_date)
);