ALTER TABLE waka.sop ADD COLUMN rmd VARCHAR;

UPDATE waka.sop SET rmd = 'Cargo Ready Date';

ALTER TABLE waka.sop alter column rmd set not null;

ALTER TABLE waka.sop_container ADD COLUMN lcl_min numeric;

DROP TABLE IF EXISTS waka.sop_sch_inv;
CREATE TABLE waka.sop_sch_inv(
	ssi_id SERIAL PRIMARY KEY,
	sop_id INT NOT NULL REFERENCES waka.sop(sop_id) ON DELETE CASCADE,
    sci_id INT NOT NULL REFERENCES waka.service_charges_inv(sci_id) ON DELETE CASCADE,
	fields JSON NULL,
	created_by INT NOT NULL REFERENCES waka.login_user(user_id) ON DELETE CASCADE,
	created_on TIMESTAMPTZ NOT NULL DEFAULT now(),
	modified_by INT REFERENCES waka.login_user(user_id) ON DELETE CASCADE,
	modified_on TIMESTAMPTZ,
	UNIQUE (sop_id, sci_id)
);

--PO Booking 

truncate table waka.sop_pob restart identity;
truncate table waka.po_booking restart identity cascade;
INSERT INTO waka.po_booking (grp, grp_seq, html_template, sub_grp, sub_grp_seq, pob_name, control_name, pob_seq, ui_img_file_name, has_child, view_text, fields, created_by) VALUES
('PO Management',1,'template2','Purchase Order Placement',1,'Purchase Order Placement','POPlacement',1,null, true,null,'[{"group":"Purchase Order Posting","fields":["field0"], "field0":{"type":"inlineedit", "field":[{"pretext":"PO must be posted to waka platform", "value":7, "posttext":"Days prior to", "range":[0,30],"controlname":"DatePriorCRD", "child":[{"type":"select", "field":[{"fieldname":"Select Data Type", "options":["Cargo Ready Date","Contract Shipment Date","Into DC Date"], "value":null, "controlname":"POPSelectDataType", "child":[]}]}]}]}},{"group":"Exception Alert for Purchase Order Uploaded","label":"The selected parties must be notified incase of an exception alert", "fields":["field0"], "field0":{"type":"select-users", "field":[{"fieldname":"Principal Details", "placeholder":"Select Principal Users", "options":[], "methodName":"getConsigneeContacts", "value":[], "controlname":"POPPUEPrincipal", "child":[{"type":"chipset", "field":[{"fieldname":"","selLabel":"", "value":[], "options":[],"unselLabel":"", "controlname": "POPPUEPrincipalUsers", "child":[]}]}]},{"fieldname":"Freight Forwarder", "placeholder":"Select Frieght Forwarder Users", "options":[], "methodName":"getFFContacts", "value":[], "controlname":"POPPUEForwarder", "child":[{"type":"chipset", "field":[{"fieldname":"","selLabel":"", "value":[], "options":[],"unselLabel":"", "controlname": "POPPUEForwarderUsers", "child":[]}]}]}]}}]',1),
('PO Management',1,'template2','Purchase Order Confirmation',2,'Purchase Order Confirmation','POConfirmation',1,null, true,null,'[{"group":"Receive PO Confirmation by Supplier", "fields":["field0"], "field0":{"type":"inlineedit", "field":[{"pretext":"Once the principal''s PO is received, the supplier must send an order confirmation within","value":"21", "posttext":"Days", "range":[0,30], "controlname":"POConfirmationBySupplier", "child":[]}]}},{"group":"Require Principal''s Reconfirmation for updates on PO details during order confirmation", "fields":["field0"], "field0":{"type":"chipset", "field":[{"fieldname":"", "selLabel":"Selected details will require approval from the principal on the updated PO details","value":["Cargo Ready Date","Loading Port","Discharching Port","Product/Item Number","Quantity","Unit Price"],"options":["Cargo Ready Date","Loading Port","Discharching Port","Product/Item Number","Quantity","Unit Price","Fumigation","Scan-and-Pack","Re-labeling","Repackaging","Compliance Check","Cargo Pick-up/Trucking","Crating","Palletisation and Slip Sheeting","Garment-on-Hanger (GOH)"], "controlname":"RRCCargoReadyDate","unselLabel":"Add more details", "child":[]}]}}]',1),
('PO Management',1,'template2','Purchase Order Progress Check',3,'Purchase Order Progress Check','ProgressCheck',1,null, true,null,'[{"group":"Date of Progress Check", "fields":["field0", "field1"], "field0":{"type":"inlineedit", "field":[{"pretext":"Progress check updates must be provided by the supplier","value":"14", "posttext":" Days prior to", "controlname":"DateOfProgressCheck", "range":[0,30], "child":[{"type":"select", "field":[{"fieldname":"Select Data Type", "options":["Cargo Ready Date","Contract Shipment Date","Into DC Date"], "value":null, "controlname":"POPSelectDataType", "child":[]}]}]}]}}]',1),
('PO Support',2,'template2','Inspection or Testing Requirements',1,'Inspection or Testing Requirements','TestingRequirements',1,null, true,null,'[{"group":"Inspection/testing standards for supplier", "fields":["field0"], "field0":{"type":"select", "field":[{"fieldname":"Select standard type", "options":["Follow PO Instructions","Set Instructions for all POs"], "value":null, "controlname":"ITRStandType", "child":[{"type":"chipset", "field":[{"fieldname":"","selLabel":"Selected Instructions", "value":[], "options":["Sampling","Production","Shipment"],"unselLabel":"Add Instructions", "controlname": "ApplyAbvSeleTo", "child":[]}]}]}]}}]',1),
('Supply Chain Support',3,'template2','Manage Supply Chain Module',1,'Manage Supply Chain Module','ManageSupplyChainModule',1,null,true,null,'[{"group":"Manage Supply Chain Module","label":"Supply chain activities of your POs are managed on the platform", "fields":["field0"], "field0":[{"controlname":"MSCModule"}]}]',1),
('Shipment Booking',4,'template2','Data for Booking Confirmation',1,'Data from Booking Confirmation','DataBookingConfirmation',1,null, true,null,'[{"group":"General Details for Booking Confirmation", "fields":["field0"], "field0":{"type":"chipset", "field":[{"fieldname":"","selLabel":"Selected details will be added to the booking confirmation data", "value":["Forwarder Booking Confirmation Number","PO Number","Item Number/SKU Number","Product Description","Ship Mode","Vessel Name","Quantity per each Item Number","Number of cartons per each Item Number","Volume per each Item Number","Total Volume per FCL Container","Total Number of Container and Size for FCL Shipment","Cargo Ready Date","Cargo Delivery Window","Voyage"],"options":["Forwarder Booking Confirmation Number","PO Number","Item Number/SKU Number","Product Description","Ship Mode","Vessel Name","Quantity per each Item Number","Number of cartons per each Item Number","Volume per each Item Number","Total Volume per FCL Container","Total Number of Container and Size for FCL Shipment","Cargo Ready Date","Cargo Delivery Window","Voyage","Equipment Type","Loading Port","Discharging Port","Place of Destination","Factory Nane","Factory Contact Person"],"unselLabel":"Add more details", "controlname": "GDForBookingConfirmation", "child":[]}]}},{"group":"Packaging Details for Booking Confirmation", "fields":["field0"], "field0":{"type":"chipset", "field":[{"fieldname":"","selLabel":"Selected details will be added to the booking confirmation data", "value":["Carton Type","Carton Length","Carton Depth","Piece per Inner","Inner per Outer","Carton Height"],"options":["Carton Type","Carton Length","Carton Depth","Piece per Inner","Inner per Outer","Inner Carton EAN","Outer Carton EAN","Carton Height"],"unselLabel":"Add more details", "controlname": "PDForBookingConf", "child":[]}]}}]',1),
('Shipment Booking',4,'template2','Grouping Criteria for Booking Confirmation',2,'Grouping Criteria for Booking Confirmation','POGroupingCriteriaBookingConfirmation',1,null, true,null,'[{"group":"Grouping Criteria", "fields":["field0"], "field0":{"type":"chipset-mandatory", "field":[{"fieldname":"","selLabel":"Selected are the mandatory details to group your POs for Booking Confirmation", "value":["Supplier","Loading Port","Discharging Port","Shipment Window","Transport Mode","Ship Mode"], "options":[],"unselLabel":"Add more details", "controlname": "SBGrpingCriteriaMandatory", "child":[]}]}},{"group":"Grouping Criteria Selection", "fields":["field0"], "field0":{"type":"chipset", "field":[{"fieldname":"","selLabel":"Selected are the additional details to group your POs for Booking Confirmation", "value":["PO Number","Pack Type"],"options":["Incoterms","PO Number","Item Type","Assortment","Pack Type","Distribution Center","HS Code","Fumigation","Compliance Check","Palletisation/Slip Sheeting","Re-Labeling","Scan-and-Pack","Repackaging"],"unselLabel":"Add more details", "controlname": "SBGrpingCriteria", "child":[]}]}}]',1),
('Shipment Booking',4,'template2','Generate Booking Confirmation to the Supplier',3,'Generate Booking Confirmation to the Supplier','GBCToSupplier',1,null, true,null,'[{"group":"Reminder to Generate Booking Confirmation","fields":["field0"], "field0":{"type":"inlineedit", "field":[{"pretext":"Reminder to generate booking confirmation between", "value":7, "posttext":"", "range":[0,30],"controlname":"RemainderToGenerate", "child":[]},{"pretext":"and", "value":7, "posttext":"days prior to", "range":[0,30], "controlname":"SBinlineEditDaysPriorTo", "child":[{"type":"select", "field":[{"fieldname":"Select Data Type", "options":["Cargo Ready Date","Contract Shipment Date","Into DC Date"], "value":null, "controlname":"POPSelectDataType", "child":[]}]}]}]}},{"group":"Include Estimated Sailing Information in Booking Confirmation","label":"", "fields":["field0"], "field0":{"type":"multi", "field":[{"fieldname":"Include Estimated Sailing Information in Booking Confirmation","label":"Estimated Sailing informationation will provide context for the booking confirmation", "value":true, "controlname":"SBIESIinBookConfirm", "child":[]}]}}]',1),
('Shipment Booking',4,'template2','Booking Reconfirmation by Supplier',4,'Booking Reconfirmation by Supplier','PORCToSupplier',1,null, true,null,'[{"group":"Final Booking Confirmation Release to Supplier","fields":["field0","field1"], "field0":{"type":"inlineedit", "field":[{"pretext":"Reminder to release final booking confirmation for FCL", "value":7, "posttext":"days prior to ETD of Vessel", "range":[0,30],"controlname":"RemainderToReleaseFBCforFCL", "child":[]}]},"field1":{"type":"inlineedit", "field":[{"pretext":"Reminder to release final booking confirmation for LCL", "value":7, "posttext":"days prior to CFS Cut off Date", "range":[0,30], "controlname": "DaysPriorToCFSforLCL", "child":[]}]}},{"group":"Booking Reconfirmation Reminder to Supplier","fields":["field0"], "field0":{"type":"inlineedit", "field":[{"pretext":"Reminder to notify supplier when booking reconfirmation is not received", "value":7, "is_alert":true, "posttext":"days prior to", "range":[0,30],"controlname":"DatePriorCRD", "child":[{"type":"select", "field":[{"fieldname":"Select Data Type", "options":["Cargo Ready Date","Contract Shipment Date","Into DC Date"], "value":null, "controlname":"POPSelectDataType", "child":[]}]}]}]}},{"group":"Require Principal''s Reconfirmation for updates on PO details during booking confirmation","label":"", "fields":["field0"], "field0":{"type":"chipset", "field":[{"fieldname":"","selLabel":"Selected details will require approval from the principal on the updated PO details", "value":["Quantity","Volume"], "options":["Quantity","Volume","Gross Weight"],"unselLabel":"Add more details", "controlname":"SBIESIinBookConfirm", "child":[]}]}}]',1),
('Shipment Booking',4,'template2','Final Booking Confirmation Details',5,'Final Booking Confirmation Details','SBFBCDetails',1,null, true,null,'[{"group":"Required final booking confirmation details for FCL","label":"", "fields":["field0"], "field0":{"type":"chipset", "field":[{"fieldname":"","selLabel":"Selected details will be shown in final booking confirmation for FCL", "value":["VGM Cutoff","ENS/AMS Cutoff","Shipment Instructions Cutoff","CY Cutoff"], "options":["VGM Cutoff","ENS/AMS Cutoff","Shipment Instructions Cutoff","CY Cutoff","Cargo Ready Date","Vessel Name","Vessel Voyage","Cargo Volume","Cargo Gross Weight","Container Type"],"unselLabel":"Add more details", "controlname": "SBRFBCFCL", "child":[]}]}},{"group":"Required final booking confirmation details for LCL","label":"", "fields":["field0"], "field0":{"type":"chipset", "field":[{"fieldname":"","selLabel":"Selected details will be shown in final booking confirmation for LCL", "value":["VGM Cutoff","ENS/AMS Cutoff","CFS Cutoff"], "options":["VGM Cutoff","ENS/AMS Cutoff","Cargo Delivery Window","CFS Cutoff","Cargo Ready Date","Vessel Name","Vessel Voyage","Cargo Volume","Cargo Gross Weight"],"unselLabel":"Add more details", "controlname": "SBRFBCLCL", "child":[]}]}}]',1),
('Shipment Authorization',5,'template2','Require authorisation on discrepancy between Purchase Order and Booking Confirmation',1,'Require authorisation on discrepancy between Purchase Order and Booking Confirmation','SARADBPOBC',1,null, true,null,'[{"group":"Require shipment authorization","label":"", "fields":["field0"], "field0":{"type":"chipset", "field":[{"fieldname":"","selLabel":"Selected details will require authorization on discrepancy", "value":["Loading Port","Discharging Port","Quantity Tolerance","Cargo Ready Date"], "options":["Loading Port","Discharging Port","Quantity Tolerance","Cargo Ready Date"],"unselLabel":"Add more details", "controlname": "SARSA", "child":[]}]}}]',1),
('Shipment Authorization',5,'template2','Booking Re-Confirmation by Supplier',2,'Booking Re-Confirmation by Supplier','SABRCBySupplier',1,null, true,null,'[{"group":"Allowed Quantity Variance at Booking Confirmation","fields":["field0"], "field0":{"type":"inlineedit", "validation":"@@SABRCAQV@@<@@SABRCAQVSecondValue@@", "field":[{"pretext":"Accepeted quanitity variance lies between", "value":-10, "posttext":"", "range":[-10,30],"controlname":"SABRCAQV", "child":[]},{"pretext":"%  to ", "value":10, "posttext":"%", "range":[0,30], "controlname":"SABRCAQVSecondValue", "child":[]}]}}]',1),
('Shipment Authorization',5,'template2','Require Shipment Re-authorization by Principal',3,'Require Shipment Re-authorization by Principal','SARSRAByPrincipal',1,null, true,null,'[{"group":"Manage discrepancy of shipment authorized details","label":"", "fields":["field0"], "field0":{"type":"chipset", "field":[{"fieldname":"","selLabel":"Selected details require re-authorization from principal if shipment authorized details are modified", "value":["ETD","ETA","Loading Port","Discharging Port"], "options":["ETD","ETA","Loading Port","Discharging Port","Product/Item Number","Quantity"],"unselLabel":"Add more details", "controlname": "SARSRAByPrincipalchipset", "child":[]}]}}]',1),
('Shipment Authorization',5,'template2','Timing of Quality Check Approval',4,'Timing of Quality Check Approval','TimingQCA',1,null,true,null,'[{"group":"Quality Check Approve", "fields":["field0"], "field0":{"type":"inlineedit", "field":[{"pretext":"Quality check approval should be conducted","value":7,"posttext":"","range":[0,30],"controlname":"VASNoShow", "child":[{"type":"select", "field":[{"fieldname":"Select Type", "posttext":"", "placeholder":"Select Type",  "options":["Before Raising the Booking Confirmation","Before Shipment Authorisation","After Shipment Authorisation"], "methodName":"getDurationType", "value":[],"controlname":"Approvaltype", "child":[]}]}]}]}}]',1);

---Document
DROP TABLE IF EXISTS waka.documents CASCADE;
CREATE TABLE waka.documents(
	doc_id SERIAL PRIMARY KEY,
	html_template VARCHAR DEFAULT 'template2',
	grp VARCHAR NOT NULL,
	grp_seq INT,
	sub_grp VARCHAR,
	sub_grp_seq INT,
	doc_name VARCHAR NOT NULL,
	control_name VARCHAR NOT NULL UNIQUE,
	doc_seq INT,
	ui_img_file_name varchar,
	has_child BOOLEAN NOT NULL default false,
	fields JSON,
	view_text VARCHAR,
	is_completed BOOLEAN DEFAULT true,
	is_alert BOOLEAN DEFAULT false,
	is_deleted BOOLEAN DEFAULT false,
	is_selected BOOLEAN,
	created_by INT NOT NULL REFERENCES waka.login_user(user_id) ON DELETE CASCADE,
	created_on TIMESTAMPTZ NOT NULL DEFAULT now(),
	modified_by INT REFERENCES waka.login_user(user_id) ON DELETE CASCADE,
	modified_on TIMESTAMPTZ
);

INSERT INTO waka.documents (grp, grp_seq, html_template, sub_grp, sub_grp_seq, doc_name, control_name, doc_seq, ui_img_file_name, has_child, view_text, fields, is_completed, is_alert, is_selected, created_by) VALUES
('Government',1,'template2','Requirement of General Documents',1,'Requirement of General Documents','ReqGenDocs',1,null, true,null,'[{"group":"Requirement of General Documents","fields":["field0"], "field0":{"type":"chipset-mandatory", "field":[{"fieldname":"","selLabel":"Selected general documents will be required", "value":["Certificate of Origin"], "options":[],"unselLabel":"", "controlname": "ReqGenDocsName", "child":[]}]}}]',false,false,null,1),
('Government',1,'template2','Requirement of Commodity Specific Documents',2,'Requirement of Commodity Specific Documents','ReqCommSpecDocs',2,null, true,null,'[{"group":"Requirement of Commodity Specific Documents","fields":["field0"], "field0":{"type":"chipset", "field":[{"fieldname":"","selLabel":"Selected commodity specific documents will be required", "value":["Electrical License"], "options":["Electrical License","Food Product Certificate"],"unselLabel":"Add more documents", "controlname": "ReqCommSpecDocsName", "child":[]}]}}]',false,false,null,1),
('Commercial',2,'template2','Requirement of Commercial Invoice',1,'Requirement of Commercial Invoice','IssCommInv',1,null, true,null,'[{"group":"Requirement of Commercial Invoice","label":"Selected commercial invoice format will be available on the platform", "fields":["field0"], "field0":{"type":"select", "field":[{"fieldname":"Select Format", "placeholder":"Select Format", "options":["Use my format","Use WAKA standard format"], "methodName":"getIssCommInvtFormat", "value":null, "controlname":"IssCommDocsSelect", "child":[{"type":"chipset-file", "field":[{"fieldname":"","selLabel":"","uploadedFileName":[], "value":[], "options":[],"unselLabel":"", "controlname": "IssCommDocsFile", "child":[]}]}]}]}},{"group":"Define the number of documents required","fields":["field0"], "field0":{"type":"inlineedit", "field":[{"pretext":"Number of originals", "value":10, "posttext":"", "range":[1,50],"controlname":"IssCommInvNoOfDocs", "child":[]},{"pretext":"and number of copies", "value":10, "posttext":"", "range":[1,50],"controlname":"IssCommInvNoofCopies", "child":[]}]}}]',false,false,true,1),
('Commercial',2,'template2','Requirement of Packing List',2,'Requirement of Packing List','IssPackList',2,null, true,null,'[{"group":"Requirement of Packing List","label":"Selected packing list format will be available on the platform", "fields":["field0"], "field0":{"type":"select", "field":[{"fieldname":"Select Format", "placeholder":"Select Format", "options":["Use my format","Use WAKA standard format"], "methodName":"getIssPackListFormat", "value":[], "controlname":"IssPackListSelect", "child":[{"type":"chipset-file", "field":[{"fieldname":"","selLabel":"","uploadedFileName":[], "value":[], "options":[],"unselLabel":"", "controlname": "IssPackListFile", "child":[]}]}]}]}},{"group":"Define the number of documents required","fields":["field0"], "field0":{"type":"inlineedit", "field":[{"pretext":"Number of originals", "value":10, "posttext":"", "range":[1,50],"controlname":"IssPackListNoOfDocs", "child":[]},{"pretext":"and number of copies", "value":10, "posttext":"", "range":[1,50],"controlname":"IssPackListNoofCopies", "child":[]}]}}]',false,false,true,1),
('Commercial',2,'template2','Requirement of MSDS (Material Safety Data Sheet)',3,'Requirement of MSDS (Material Safety Data Sheet)','IssMsds',3,null, true,null,'[{"group":"Requirement of MSDS (Material Safety Data Sheet)","label":"MSDS document will be managed by Freight Forwarder", "fields":["field0"], "field0":[{"controlname":"IssMsdsName"}]}]',false,false,true,1),
('Shipping',3,'template2','Requirement of Forwarders Cargo Receipt/ House Bill of Lading/ House Sea Waybill',1,'Requirement of Forwarders Cargo Receipt/ House Bill of Lading/ House Sea Waybill','ReqForCargoBills',1,null, true,null,'[{"group":"Selected document type that needs to be required ", "fields":["field0"], "field0":{"type":"chipset", "field":[{"fieldname":"",  "selLabel":"Selected parties","options":["Forwarders Cargo Receipt","House Bill of Lading/ House Sea Waybill"], "value":["Forwarders Cargo Receipt","House Bill of Lading/ House Sea Waybill"], "controlname":"IssForCargoBillsDocType","unselLabel":"Unselected parties", "child":[]}]}},{"group":"Define the number of documents required","fields":["field0"], "field0":{"type":"inlineedit", "field":[{"pretext":"Number of originals", "value":10, "posttext":"and number of copies", "range":[1,50],"controlname":"IssForCargoRemainderToGenerate", "child":[]},{"pretext":"", "value":10, "posttext":"", "range":[1,50],"controlname":"IssForCargoNoofCopies", "child":[]}]}},{"group":"Reminder for issuance of documents","is_alert":true ,"fields":["field0"], "field0":{"type":"inlineedit", "field":[{"pretext":"FCR/HBL to be issued", "value":7, "posttext":"days after", "range":[0,30],"controlname":"FCRRemainderToGenerate", "child":[{"type":"select", "field":[{"fieldname":"Select Data Type", "options":["Cargo Receiving Date","CFS Cutoff Date"], "value":null, "controlname":"FCRSelectDataType", "child":[]}]}]}]}},{"group":"","fields":["field0"], "field0":{"type":"multi", "field":[{"fieldname":"House Bill of Lading or House Sea WayBill must be dated and issued on the day the cargoes are shipped on board", "value":true, "controlname":"HouseBillIssued", "child": []},{"fieldname":"Remarks on the conditions of the cargoes as stipulated on the Dock Receipts are to be stated on the FCR or House Bill of Lading or House Sea Waybill or House Sea Waybill", "value":true, "controlname":"RemarkCargoDock", "child": []},{"fieldname":"Issue Received of Shipment FCR for overflow of cargoes", "value":true, "controlname":"IssueReceiveShip", "child": []},{"fieldname":"Allow issue one set of FCR or House Bill of Lading or House Sea Waybill per split shipment", "value":true, "controlname":"AllowIssueFCR", "child": []}]}},{"group":"Selected party types and the respective details will be mentioned in the issued documents", "fields":["field0"], "field0":{"type":"chipset", "field":[{"fieldname":"",  "selLabel":"Selected parties","options":["Notify Party","Supplier","Principal"], "value":["Supplier","Principal"], "controlname":"IssForCargoBillsSelectedParty","unselLabel":"Unselected parties", "child":[]}]}}]',false,true,true,1),
('Shipping',3,'template2','Requirement of Master Bill of Lading/Sea Waybill',2,'Requirement of Master Bill of Lading/Sea Waybill','IssMasterBills',2,null, true,null,'[{"group":"Selected document type that needs to be issued ", "fields":["field0"], "field0":{"type":"chipset", "field":[{"fieldname":"",  "selLabel":"Selected parties","options":["Forwarders Cargo Receipt","House Bill of Lading/ House Sea Waybill"], "value":["Forwarders Cargo Receipt","House Bill of Lading/ House Sea Waybill"], "controlname":"IssMasterBillsDocType","unselLabel":"Unselected parties", "child":[]}]}},{"group":"Define the number of documents required","fields":["field0"], "field0":{"type":"inlineedit", "field":[{"pretext":"Number of originals", "value":10, "posttext":"and number of copies", "range":[1,50],"controlname":"IssMasterBillsRemainderToGenerate", "child":[]},{"pretext":"", "value":10, "posttext":"", "range":[1,50],"controlname":"IssMasterBillstNoofCopies", "child":[]}]}},{"group":"Reminder for issuance of documents","label":"","is_alert":true, "fields":["field0"], "field0":{"type":"inlineedit", "field":[{"pretext":"Master Bill of Lading/Sea WayBill to be issued", "value":7, "posttext":"days after Vessel Departure Date", "range":[0,30],"controlname":"MasterFCRRemainderToGenerate", "child":[]}]}},{"group":"","fields":["field0"], "field0":{"type":"multi", "field":[{"fieldname":"House Bill of Lading or House Sea WayBill must be dated and issued on the day the cargoes are shipped on board", "value":true, "controlname":"MasterHouseBillIssued", "child": []},{"fieldname":"Remarks on the conditions of the cargoes as stipulated on the Dock Receipts are to be stated on the FCR or House Bill of Lading or House Sea Waybill or House Sea Waybill", "value":true, "controlname":"MasterRemarkCargoDock", "child": []},{"fieldname":"Issue Received of Shipment FCR for overflow of cargoes", "value":true, "controlname":"MasterIssueReceiveShip", "child": []},{"fieldname":"Allow issue one set of FCR or House Bill of Lading or House Sea Waybill per split shipment", "value":true, "controlname":"MasterAllowIssueFCR", "child": []}]}},{"group":"Selected party types and the respective details will be mentioned in the issued documents", "fields":["field0"], "field0":{"type":"chipset", "field":[{"fieldname":"",  "selLabel":"Selected parties","options":["Notify Party","Supplier","Principal"], "value":["Supplier","Principal"], "controlname":"IssMasterBillsSelectedParty","unselLabel":"Unselected parties", "child":[]}]}}]',false,true,true,1),
('Shipping',3,'template2','Requirement of Bill of Lading/Sea Waybill from Coloader',3,'Requirement of Bill of Lading/Sea Waybill from Coloader','IssColoaderBills',2,null, true,null,'[{"group":"Define the number of documents required","fields":["field0"], "field0":{"type":"inlineedit", "field":[{"pretext":"Number of originals", "value":10, "posttext":"and number of copies", "range":[1,50],"controlname":"IssColoaderBillsNoofCopies", "child":[]},{"pretext":"", "value":10, "posttext":"", "range":[1,50],"controlname":"IssColoaderBillsNoofCopiesName", "child":[]}]}},{"group":"Reminder for issuance of documents","label":"", "is_alert":true ,"fields":["field0"], "field0":{"type":"inlineedit", "field":[{"pretext":"FCR/HBL to be issued", "value":7, "posttext":"days after Vessel Departure", "range":[0,30],"controlname":"RemIssDoc", "child":[]}]}},{"group":"","fields":["field0"], "field0":{"type":"multi", "field":[{"fieldname":"Issue One Single House Bill of Lading/Sea Waybill if Containers with same Ship Mode, From same Loading Port, To same Discharging Port, on the same Vessel Voyage and Carrier", "value":true, "controlname":"IssShipMode", "child": []}]}},{"group":"Selected party types and the respective details will be mentioned in the issued documents", "fields":["field0"], "field0":{"type":"chipset", "field":[{"fieldname":"",  "selLabel":"Selected parties","options":["Notify Party","Supplier","Principal"], "value":["Supplier","Principal"], "controlname":"IssShipModeSelectedParty","unselLabel":"Unselected parties", "child":[]}]}}]',false,true,true,1),
('Shipping',3,'template2','Requirement of Master Air Waybill and House Air Waybill',4,'Requirement of Master Air Waybill and House Air Waybill','IssMasterAirBills',2,null, true,null,'[{"group":"Define the number of documents required","fields":["field0"], "field0":{"type":"inlineedit", "field":[{"pretext":"Number of originals", "value":10, "posttext":"and number of copies", "range":[1,50],"controlname":"IssMasterAirBillsNoOfCopies", "child":[]},{"pretext":"", "value":10, "posttext":"", "range":[1,50],"controlname":"IssMasterAirBillsNoOfCopiesName", "child":[]}]}},{"group":"Selected party types and the respective details will be mentioned in the issued documents", "fields":["field0"], "field0":{"type":"chipset", "field":[{"fieldname":"",  "selLabel":"Selected parties","options":["Notify Party","Supplier","Principal"], "value":["Supplier","Principal"], "controlname":"IssMasterAirBillsSelectedParty","unselLabel":"Unselected parties", "child":[]}]}}]',false,false,true,1),
('Shipping',3,'template2','Requirement of Container Manifest',5,'Requirement of Container Manifest','IssContManifest',2,null, true,null,'[{"group":"Requirement of Container Manifest","label":"Require a copy to be affixed to the inside of the container`s door", "fields":["field0"], "field0":[{"controlname":"IssContManifestName"}]}]',false,false,null,1),
('Documents Despatch',4,'template2','Reminder to Generate Documents Despatch',1,'Reminder to Generate Documents Despatch','RemGenDocsDis',1,null, true,null,'[{"group":"Reminder to Generate Documents Despatch","label":"", "is_alert":true ,"fields":["field0"], "field0":{"type":"inlineedit", "field":[{"pretext":"Documents will be despatched", "value":7, "posttext":"days after Vessel Departure", "range":[0,30],"controlname":"RemGenDocsDisName", "child":[]}]}}]',false,true,null,1),
('Documents Despatch',4,'template2','Document Despatch to Parties',2,'Document Despatch to Parties','DocDispToParty',2,null, true,null,'[{"group":"Document Despatch to Parties","label":"Selected parties will receive despatched documents", "fields":["field0"], "field0":{"type":"select-users", "field":[{"fieldname":"Principal Details", "placeholder":"Select Principal Users", "options":[], "methodName":"getConsigneeContacts", "value":[], "controlname":"DocDispToPartyPrincipal", "child":[{"type":"chipset", "field":[{"fieldname":"","selLabel":"", "value":[], "options":[],"unselLabel":"", "controlname": "DocDispToPrincipalUsers", "child":[]}]}]},{"fieldname":"Freight Forwarder", "placeholder":"Select Frieght Forwarder Users", "options":[], "methodName":"getFFContacts", "value":[], "controlname":"DocDispToPartyForwarder", "child":[{"type":"chipset", "field":[{"fieldname":"","selLabel":"", "value":[], "options":[],"unselLabel":"", "controlname": "DocDispToForwarderUsers", "child":[]}]}]}]}}]',false,false,null,1);

-- Deleted service type name "Others" 
DELETE FROM waka.services WHERE service_id = 51 ;

INSERT INTO waka.services (service_type_id, service_name, input_required,created_by,is_mandatory) VALUES((SELECT lookup_name_id FROM waka.lookup_name WHERE lookup_name='Shipment Tracking Services'),'Packaging & Artwork Sign Off',false,1,true);
INSERT INTO waka.services (service_type_id, service_name, input_required,created_by,is_mandatory) VALUES((SELECT lookup_name_id FROM waka.lookup_name WHERE lookup_name='Shipment Tracking Services'),'Production Sample Sign Off',false,1,true);
INSERT INTO waka.services (service_type_id, service_name, input_required,created_by,is_mandatory) VALUES((SELECT lookup_name_id FROM waka.lookup_name WHERE lookup_name='Shipment Tracking Services'),'Pre Shipment Inspection',false,1,true);
INSERT INTO waka.services (service_type_id, service_name, input_required,created_by,is_mandatory) VALUES((SELECT lookup_name_id FROM waka.lookup_name WHERE lookup_name='Shipment Tracking Services'),'GS1 Barcode Attachment',false,1,true);
INSERT INTO waka.services (service_type_id, service_name, input_required,created_by,is_mandatory) VALUES((SELECT lookup_name_id FROM waka.lookup_name WHERE lookup_name='Shipment Tracking Services'),'Production Progress Check',false,1,true);
INSERT INTO waka.services (service_type_id, service_name, input_required,created_by,is_mandatory) VALUES((SELECT lookup_name_id FROM waka.lookup_name WHERE lookup_name='Shipment Tracking Services'),'Shipment Bookings',false,1,true);
INSERT INTO waka.services (service_type_id, service_name, input_required,created_by,is_mandatory) VALUES((SELECT lookup_name_id FROM waka.lookup_name WHERE lookup_name='Shipment Tracking Services'),'Origin Cargo Deliveries',false,1,true);
INSERT INTO waka.services (service_type_id, service_name, input_required,created_by,is_mandatory) VALUES((SELECT lookup_name_id FROM waka.lookup_name WHERE lookup_name='Shipment Tracking Services'),'Documentation Availability',false,1,true);
INSERT INTO waka.services (service_type_id, service_name, input_required,created_by,is_mandatory) VALUES((SELECT lookup_name_id FROM waka.lookup_name WHERE lookup_name='Shipment Tracking Services'),'In Cartage provider’s Yard Date',false,1,true);
INSERT INTO waka.services (service_type_id, service_name, input_required,created_by,is_mandatory) VALUES((SELECT lookup_name_id FROM waka.lookup_name WHERE lookup_name='Shipment Tracking Services'),'Vessel Departure',false,1,false);
INSERT INTO waka.services (service_type_id, service_name, input_required,created_by,is_mandatory) VALUES((SELECT lookup_name_id FROM waka.lookup_name WHERE lookup_name='Shipment Tracking Services'),'Inbound Customs Clearance',false,1,false);
INSERT INTO waka.services (service_type_id, service_name, input_required,created_by,is_mandatory) VALUES((SELECT lookup_name_id FROM waka.lookup_name WHERE lookup_name='Shipment Tracking Services'),'Available at Wharf',false,1,false);
INSERT INTO waka.services (service_type_id, service_name, input_required,created_by,is_mandatory) VALUES((SELECT lookup_name_id FROM waka.lookup_name WHERE lookup_name='Shipment Tracking Services'),'DC Booking Made',false,1,false);
INSERT INTO waka.services (service_type_id, service_name, input_required,created_by,is_mandatory) VALUES((SELECT lookup_name_id FROM waka.lookup_name WHERE lookup_name='Shipment Tracking Services'),'DC Delivery Date',false,1,false);
INSERT INTO waka.services (service_type_id, service_name, input_required,created_by,is_mandatory) VALUES((SELECT lookup_name_id FROM waka.lookup_name WHERE lookup_name='Shipment Tracking Services'),'DC Unpack Date',false,1,false);
INSERT INTO waka.services (service_type_id, service_name, input_required,created_by,is_mandatory) VALUES((SELECT lookup_name_id FROM waka.lookup_name WHERE lookup_name='Shipment Tracking Services'),'Empty Container available for pick up date',false,1,false);
INSERT INTO waka.services (service_type_id, service_name, input_required,created_by,is_mandatory) VALUES((SELECT lookup_name_id FROM waka.lookup_name WHERE lookup_name='Shipment Tracking Services'),'Empty Container taken away date',false,1,false);

-- Cargo Handling - LCL Free Storage Requirements

DROP TABLE IF EXISTS waka.sop_orgin_port_details;
CREATE TABLE waka.sop_orgin_port_details (
	sop_opd_id SERIAL NOT NULL PRIMARY KEY,
	sop_id INT NOT NULL REFERENCES waka.sop(sop_id) ON DELETE CASCADE,
	origin_port_id INT NOT NULL REFERENCES waka.port(port_id) ON DELETE CASCADE,
	port_name VARCHAR NOT NULL,
    free_storage_days INT REFERENCES waka.lookup_name(lookup_name_id),
	free_storage_days_validity INT REFERENCES waka.lookup_name(lookup_name_id),
	created_by INT NOT NULL REFERENCES waka.login_user(user_id) ON DELETE CASCADE,
	created_on TIMESTAMPTZ NOT NULL DEFAULT now(), 
	modified_by INT REFERENCES waka.login_user(user_id) ON DELETE CASCADE,
	modified_on TIMESTAMPTZ,
	UNIQUE (sop_id, origin_port_id)
);

INSERT INTO waka.sop_orgin_port_details (sop_id, origin_port_id, port_name, created_by)
SELECT sop_id, sp.origin_port_id, p.port_name, sp.created_by  FROM waka.port p JOIN waka.sop_port sp ON sp.origin_port_id = p.port_id GROUP BY port_name, sp.origin_port_id, sop_id, sp.created_by;

INSERT INTO waka.lookup_type (lookup_type, display_name, description, created_by) VALUES
('free_storage_days_validity', 'Validity for Free Storage Days', 'Free Storage Details for LCL in Cargo Requirements', 1);

